[workspace]
resolver = "3"
members = [
    "gitlab-tracker",
    "gitlab-tracker-notify",
    "gitlab-tracker-core",
    "gitlab-tracker-redmine",
]

[workspace.package]
version = "0.4.2"
authors = ["Julien Langlois <julien@julienlanglois.fr>"]
edition = "2021"
license = "MIT"
repository = "https://github.com/julien-langlois/gitlab-tracker"

[workspace.dependencies]
generic-array = "0.14.9"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
strip = true
